apiVersion: apps/v1
kind: Deployment
metadata:
  name: $appname
spec:
  selector:
    matchLabels:
      app: $appname
  replicas: $replicas
  template:
    metadata:
      labels:
        app: $appname
    spec:
      containers:
        - env:
          name: $appname
          image: $image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: $port
          resources:
            limits:
              cpu: 2
              memory: 8Gi
            requests:
              cpu: 2
              memory: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: $appname
  name: $appname
spec:
  ports:
  - port: $port
    targetPort: $targetport
  selector:
    app: $appname
  type: LoadBalancer
